export const Users = [
  {
    id:1,
    profilePicture: "person/1.1.jpg",
    username: "Safak Kocaoglu",
  },
  {
    id:2,
    profilePicture: "person/2.jpg",
    username: "Winston Churchill",
  },
  {
    id:3,
    profilePicture: "person/3.jpg",
    username: "Jacinda Methews",
  },
  {
    id:4,
    profilePicture: "person/4.jpg",
    username: "Nelson",
  },
  {
    id:5,
    profilePicture: "person/5.jpg",
    username: "Thomas Holder",
  },
  {
    id:6,
    profilePicture: "person/1.1.jpg",
    username: "Sherry Beauchamp",
  },
  {
    id:7,
    profilePicture: "person/2.jpg",
    username: "Travis",
  },
  {
    id:8,
    profilePicture: "person/3.jpg",
    username: "Kristen",
  },
  {
    id:9,
    profilePicture: "person/4.jpg",
    username: "Abdul Bari",
  },
  {
    id:10,
    profilePicture: "person/5.jpg",
    username: "Sabir Shakir",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "JS cheat sheet",
    photo: "post/JS cheatsheet.jpg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
    share:1,
    dislike:0,
  },
  {
    id: 2,
    photo: "post/Linear regression.jpg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    dislike:3,
    comment: 1,
    share:2,
  },
  {
    id: 3,
    desc: "Control Structures in C++",
    photo: "post/Control Structures in C++.mp4",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
    share:1,
    dislike:0,
  },
  {
    id: 4,
    photo: "post/migrations in ROR.jpg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
    share:1,
    dislike:0,
  },
  {
    id: 5,
    photo: "post/python.jpg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
    share:2,
    dislike:0,
  },
  {
    id: 6,
    video: "post/Destructors in C++.mp4",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
    share:4,
    dislike:5,
  },
  {
    id: 7,
    desc: "C++ in 100 Seconds",
    video: "post/C++ in 100 Seconds.mp4",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
    share:5,
    dislike:9,
  },
  {
    id: 8,
    photo: "post/Input an Integer in C++.mp4",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
    share:1,
    dislike:3,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "post/9.jpeg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
    share:0,
    dislike:1,
  },
  {
    id: 10,
    photo: "post/10.jpeg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
    share:5,
    dislike:2,
  },
];